#
# Example pgdog.toml configuration file.
#
[general]
host = "0.0.0.0"
port = 6432
min_pool_size = 1
shutdown_timeout = 5_000

[[databases]]
name = "pgdog"
role = "primary"
host = "127.0.0.1"
port = 5432
database_name = "pgdog"

[[plugins]]
name = "pgdog_routing"
