name: package
on:
  push:
    branches:
      - main

jobs:
  package:
    strategy:
      matrix:
        os:
          - ["ubuntu-24.04", "linux/amd64"]
          - ["ubuntu-24.04-arm", "linux/arm64"]
    runs-on: ${{ matrix.os.0 }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Determine tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pgdogdev/pgdog
          tags: |
            type=sha,prefix=,format=long
            type=schedule
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{ is_default_branch }}
      - name: Login into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ghcr.io/pgdogdev/pgdog
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.os.1 }}
          provenance: false
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
